### ISSUE TITLE
Handle `Quote` (specifically Quote3)

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/sgx#66]
- [x] Look at pulling nom in for converting bytes to the types

**Comment by nick-mobilecoin** [comment]
Discussion from 2022-08-16:
* Create a rust type that holds a `Vec<u8>`. This will be the raw quote.  
  * The need to have this raw representation is to be able to verify the signatures on parts of these raw bytes.
* Create a rust type for each of the SGX quote types, `sgx_quote_t`, `sgx_quote3_t`, and `sgx_quote4_t`.
  * Initial thought was a view, but with https://github.com/rust-lang/rust/issues/82523 we think we'll need to copy out instead of being able to pass references.
  * `sgx_quote_t` looks to be EPID, `sgx_quote3_t` looks to be DCAP, and `sgx_quote4_t` looks to be for TDX

**Comment by jcape** [comment]
Thoughts as of today's sprint-planning: Quote3 is a rustic structure that contains the parsed Quote bytes, as well as the underlying bytes (as slice or vec).

**Comment by nick-mobilecoin** [comment]
Implemented via #190, #196, #197, #200, #202, #203, #204, #205, #208
